// Promotions: the platform-neutral discounts the editor, forms and journeys
// reference by id. Codes are generated by the promotion engine, pushed to the
// store by its adapter, and tracked here.
import { NextRequest } from "next/server";
import { z } from "zod";
import { db } from "@/lib/server/db";
import { audit } from "@/lib/server/audit";
import { currentUser } from "@/lib/server/permissions";
import { promotionLabel } from "@/lib/server/promotions";

export async function GET() {
  const user = await currentUser();
  if (!user) return Response.json({ ok: false }, { status: 401 });

  const promotions = await db.promotion.findMany({
    where: { workspaceId: user.workspaceId },
    include: { _count: { select: { codes: true } } },
    orderBy: { createdAt: "desc" },
  });

  const rows = await Promise.all(
    promotions.map(async (p) => {
      const [redeemed, pending, pushed] = await Promise.all([
        db.couponCode.count({ where: { promotionId: p.id, redeemedAt: { not: null } } }),
        db.couponCode.count({ where: { promotionId: p.id, pushState: "pending" } }),
        db.couponCode.count({ where: { promotionId: p.id, pushState: "pushed" } }),
      ]);
      return {
        id: p.id, name: p.name, mode: p.mode, sharedCode: p.sharedCode, prefix: p.prefix,
        label: promotionLabel(p), kind: p.kind, amount: p.amount, currency: p.currency,
        expiryDays: p.expiryDays, minSpend: p.minSpend, usageLimit: p.usageLimit,
        archived: p.archived, storeId: p.storeId,
        issued: p._count.codes, redeemed, pendingPush: pending, pushed,
      };
    })
  );

  return Response.json({ ok: true, promotions: rows });
}

const Upsert = z.object({
  id: z.string().optional(),
  name: z.string().min(1).max(120),
  storeId: z.string().nullable().optional(),
  mode: z.enum(["shared", "unique"]).default("unique"),
  sharedCode: z.string().max(40).nullable().optional(),
  prefix: z.string().min(2).max(10).regex(/^[A-Z0-9]+$/, "Prefix: capitals and digits only.").default("LOOM"),
  kind: z.enum(["percent", "fixed", "free_shipping"]).default("percent"),
  amount: z.number().min(0).max(100000).default(10),
  currency: z.string().length(3).default("GBP"),
  expiryDays: z.number().int().min(1).max(365).nullable().optional(),
  minSpend: z.number().min(0).nullable().optional(),
  maxSpend: z.number().min(0).nullable().optional(),
  usageLimit: z.number().int().min(1).nullable().optional(),
  perCustomer: z.number().int().min(1).nullable().optional(),
  individualUse: z.boolean().default(true),
  emailRestricted: z.boolean().default(true),
  archived: z.boolean().optional(),
});

export async function POST(req: NextRequest) {
  const user = await currentUser();
  if (!user) return Response.json({ ok: false }, { status: 401 });

  const parsed = Upsert.safeParse(await req.json().catch(() => null));
  if (!parsed.success) {
    return Response.json({ ok: false, error: parsed.error.issues[0]?.message ?? "Check the promotion." }, { status: 400 });
  }
  const { id, ...data } = parsed.data;

  if (data.mode === "shared" && !data.sharedCode) {
    return Response.json({ ok: false, error: "A shared promotion needs its code (e.g. WELCOME10)." }, { status: 400 });
  }
  if (data.storeId) {
    const store = await db.store.findFirst({ where: { id: data.storeId, workspaceId: user.workspaceId } });
    if (!store) return Response.json({ ok: false, error: "That store is not in this workspace." }, { status: 400 });
  }

  if (id) {
    const owned = await db.promotion.findFirst({ where: { id, workspaceId: user.workspaceId } });
    if (!owned) return Response.json({ ok: false, error: "Promotion not found." }, { status: 404 });
    const p = await db.promotion.update({ where: { id }, data });
    await audit(user.workspaceId, user.email, "promotion.updated", `'${p.name}'`);
    return Response.json({ ok: true, id: p.id });
  }

  const p = await db.promotion.create({ data: { workspaceId: user.workspaceId, ...data } });
  await audit(user.workspaceId, user.email, "promotion.created", `'${p.name}' · ${p.mode} · ${promotionLabel(p)}`);
  return Response.json({ ok: true, id: p.id });
}
